### ISSUE TITLE
Boytz's Knickknacks Store in Bastok - Missing updated textures

### ISSUE THREAD

**Issue by andre-macc** [Ashenbubs/AshenbubsHD-Beta#1]
This store in Bastok Mines (Gelzerio's store) has a mix of updated an old textures:

![image](https://user-images.githubusercontent.com/72416751/102299458-beaeb480-3f31-11eb-9ba1-2ff760712a51.png)

![image](https://user-images.githubusercontent.com/72416751/102299482-ca01e000-3f31-11eb-891b-cda9b76bd661.png)

![image](https://user-images.githubusercontent.com/72416751/102299523-d8e89280-3f31-11eb-9475-e82a5ca143e3.png)

![image](https://user-images.githubusercontent.com/72416751/102299565-e9990880-3f31-11eb-9937-fb23ba25021d.png)

**Comment by Ashenbubs** [comment]
Damn - Okay, so I found the file - ROM/1/52.DAT

However, the DAT itself doesn't contain those textures, meaning it must be obtaining it from elsewhere, or, hm... this is a new one.

I'll keep checking - Thanks for letting me know!

![image](https://user-images.githubusercontent.com/61240482/102325137-b464d880-3f7a-11eb-8fc8-8d282955bbd7.png)

**Comment by Ashenbubs** [comment]
Aha - Found them - 2 hidden dds files... Going to have to upscale and hex-edit these two bad boys in~

Will do this later today.

![image](https://user-images.githubusercontent.com/61240482/102326466-5507c800-3f7c-11eb-9811-a978e6eb86be.png)

**Comment by Ashenbubs** [comment]
Ooft.

Good news, found the problem.

Bad news, it can't be resolved yet as DXT1 files handle completely differently from DXT3 files in Hex Editors and it's a little trial-and-error to resolve.

I've made a tag just for these kind of DXT1 issues, and I'll re-open this and any others found once a solution has been found!
