### ISSUE TITLE
Cleaning Tool Set Texture Missing

### ISSUE THREAD

**Issue by graveb0und** [Ashenbubs/AshenbubsHD-Beta#5]
Just noticed this when I was changing jobs in my Mog House.

![Untitled2](https://user-images.githubusercontent.com/76702612/103235213-833bbf00-490f-11eb-9970-aa7128711d2a.png)

**Comment by Ashenbubs** [comment]
Thank Grave. Looks like the alpha layer got switched with the main layer! I’ll go through and take a look!

**Comment by Ashenbubs** [comment]
Finally found this - Seems to be a mistake on SE's behalf - The alpha channel is reversed somehow - Which explains why only the tips of the model actually show.

Will be adding this DAT file shortly - In the meantime, it's location is ROM/75/6.DAT and I'll attach the file that'll resolve.

[6.zip](https://github.com/Ashenbubs/AshenbubsHD-Beta/files/6046365/6.zip)
