### ISSUE TITLE
Tide Bold Font

### ISSUE THREAD

**Issue by Siushaga** [Ashenbubs/AshenbubsHD-Beta#6]
Hello!

Noticed that you included your font here:
https://github.com/Ashenbubs/AshenbubsHD-Beta/blob/main/New%20Fonts/Tide%20Bold/ROM/119/51.DAT

If possible, would you be able to also upload this as the underlying .dds file? Unfortunately, 119/51.DAT shares many components for the UI as well, such as cursor pointer mods, etc. Would be nice to be able to utilize ChangeTex.exe to inject the overwritten font type this way.

You're doing awesome stuff!

**Comment by Ashenbubs** [comment]
I’ll add the .DDS file for that font and the icons separately tomorrow morning when I wake up :)

**Comment by Ashenbubs** [comment]
Added the two dds files for you! :)
