### ISSUE TITLE
Blurry Lilisette

### ISSUE THREAD

**Issue by Aleuric** [Ashenbubs/AshenbubsHD-Beta#7]
![JA2oeUB](https://user-images.githubusercontent.com/78052256/105911829-9918ce80-5ff8-11eb-8630-116bbe2ccd0d.jpeg)

Idk if this is a bug or if she's supposed to look like this. I'm new to this game and when I found your HD Beta Project I was blown away. Thanks for all your work. The game looks incredible with your HD mods. Its been a real pleasure to experience the game at this level of detail.

**Comment by Ashenbubs** [comment]
Hey Aleuric!

This effect is found on several models in the game, it’s a blur/magic type effect that looked good on PS2 but didn’t turn out great on PC. You’ll see it on any tier II trust (IE: Lilsette II, Lion II, Zeid II, etc) as well as any Summon/Avatar. 

You can turn it off via this in-game command, it’s an actual FFXI Setting so not bound to windower/Ashita:

/localsettings blureffect off

FFXI will save this setting for all future times you log in. Glad to hear you’re enjoying everything!

**Comment by Aleuric** [comment]
It all makes sense now. Thanks.
