### ISSUE TITLE
Galka Malignance Gloves

### ISSUE THREAD

**Issue by Tathamet667** [Ashenbubs/AshenbubsHD-Beta#8]
Any potential fix for this issue?

https://www.ffxiah.com/forum/topic/51963/ffxi-hd-mods/42/#3565523

**Comment by Ashenbubs** [comment]
Hm - Wondering if this may be something from an older version?  I can see them in mine at the moment:

![image](https://user-images.githubusercontent.com/61240482/108591561-431e1900-7361-11eb-9a51-61f822826dab.png)

Is there a file in your last download of this for:
ROM/362/74.DAT

These are the hands, might need to update something maybe?

**Comment by Tathamet667** [comment]
[74.zip](https://github.com/Ashenbubs/AshenbubsHD-Beta/files/6017165/74.zip)

This is what I have from ROM/362  I last updated in January.  I'll try a more recent version.

**Comment by Tathamet667** [comment]
No change when using the most recent copy of ROM/362/74.DAT.  But... I kept playing around and noticed they maybe the issue is the body?  When I change the body armor my gloves magically appear.  Is Jhakri Robe the cause?

Chocobo Shirt:
![image](https://user-images.githubusercontent.com/65053603/108615149-029cba80-73b6-11eb-8bdb-2c40fd19557e.png)

Aurore Doublet:
![image](https://user-images.githubusercontent.com/65053603/108615171-3aa3fd80-73b6-11eb-9af6-72306cbcdefb.png)

Jhakri Robe:
![image](https://user-images.githubusercontent.com/65053603/108615193-53acae80-73b6-11eb-8e39-1a70e17fdc1a.png)

**Comment by Tathamet667** [comment]
I realize you moved out of beta (and almost moved to nexusmods), but just wanted to provide an update.

I download the basis edition from nexusmods today and the issue still remains.  Malignance Gloves with something other than Jhakri Robe +2 loads just fine.  Oddly enough I don't have this issue when using other gloves paired with Jhakri Robe.  Were you able to recreate the issue?  Tell me I'm not crazy :)

**Comment by Ashenbubs** [comment]
I finally found it this morning!  My god what a headache!!

Attached is the fix for the gloves - Place this 72.DAT into .../ROM/362/ and replace the 72.DAT file there.

I'll add this to the new versions shortly.  So sorry for the wait Tathamet!


[ROM - 362 - 72.zip](https://github.com/Ashenbubs/AshenbubsHD-Beta/files/6114639/ROM.-.362.-.72.zip)
